CREATE TABLE Carac (idCarac INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (idCarac), TypeCarac_idCarac INTEGER, Reference_idReference INTEGER, Value VARCHAR(255));
CREATE TABLE ShipmentFee (idShipmentFee INTEGER NOT NULL AUTO_INCREMENT, Product_idProduct INTEGER, Supplier_idSupplier INTEGER, PRIMARY KEY (idShipmentFee));
CREATE TABLE Reference (idReference INTEGER NOT NULL AUTO_INCREMENT, Product_idReference INTEGER, Carac_idCarac INTEGER, Item_idItem INTEGER, PRIMARY KEY (idReference));
CREATE TABLE Item (idItem INTEGER NOT NULL AUTO_INCREMENT, Count INTEGER, Order_idOrder INTEGER, PRIMARY KEY (idItem));
CREATE TABLE Supplier (idSupplier INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (idSupplier), Label VARCHAR(255) NOT NULL);
CREATE TABLE Stock (idStock INTEGER NOT NULL AUTO_INCREMENT, Reference_idReference INTEGER, Supplier_idSupplier INTEGER, PRIMARY KEY (idStock));
CREATE TABLE TypeCarac (idTypeCarac INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (idTypeCarac), Label VARCHAR(255) NOT NULL, DicoCarac_idCarac INTEGER);
CREATE TABLE DicoCarac (idDicoCarac INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (idDicoCarac));
CREATE TABLE Familly (idFamilly INTEGER NOT NULL AUTO_INCREMENT, Label VARCHAR(255) NOT NULL, Familly_idFamilly INTEGER, PRIMARY KEY (idFamilly), DicoCarac_idFamilly INTEGER);
CREATE TABLE Product (idProduct INTEGER NOT NULL AUTO_INCREMENT, Label VARCHAR(255) NOT NULL, LongLabel VARCHAR(255) NOT NULL, Price INTEGER, Familly_idProduct INTEGER, DicoMedia_idProduct INTEGER, PRIMARY KEY (idProduct));
CREATE TABLE Customer (idCustomer INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (idCustomer));
CREATE TABLE DicoMedia (idDicoMedia INTEGER NOT NULL AUTO_INCREMENT,PRIMARY KEY (idDicoMedia));
CREATE TABLE Media (idMedia INTEGER NOT NULL AUTO_INCREMENT, DicoMedia_idMedia INTEGER, FilePath VARCHAR(255), PRIMARY KEY (idMedia));
ALTER TABLE ShipmentFee ADD CONSTRAINT FK_ShipmentFee_Supplier_idSupplier FOREIGN KEY (Supplier_idSupplier) REFERENCES Supplier (idSupplier);
ALTER TABLE Reference ADD CONSTRAINT FK_Reference_Carac_idCarac FOREIGN KEY (Carac_idCarac) REFERENCES Carac (idCarac);
ALTER TABLE Reference ADD CONSTRAINT FK_Reference_Item_idItem FOREIGN KEY (Item_idItem) REFERENCES Item (idItem);
ALTER TABLE Stock ADD CONSTRAINT FK_Stock_Supplier_idSupplier FOREIGN KEY (Supplier_idSupplier) REFERENCES Supplier (idSupplier);
ALTER TABLE Stock ADD CONSTRAINT FK_Stock_Reference_idReference FOREIGN KEY (Reference_idReference) REFERENCES Reference (idReference);
ALTER TABLE Familly ADD CONSTRAINT FK_Familly_Familly_idFamilly FOREIGN KEY (Familly_idFamilly) REFERENCES Familly (idFamilly);
ALTER TABLE Product ADD CONSTRAINT FK_Product_Familly_idProduct FOREIGN KEY (Familly_idProduct) REFERENCES Familly (idFamilly);
ALTER TABLE Reference ADD CONSTRAINT FK_Reference_Product_idReference FOREIGN KEY (Product_idReference) REFERENCES Product (idProduct);
ALTER TABLE Familly ADD CONSTRAINT FK_Familly_DicoCarac_idFamilly FOREIGN KEY (DicoCarac_idFamilly) REFERENCES DicoCarac (idDicoCarac);
ALTER TABLE Carac ADD CONSTRAINT FK_Carac_TypeCarac_idCarac FOREIGN KEY (TypeCarac_idCarac) REFERENCES TypeCarac (idTypeCarac);
ALTER TABLE Carac ADD CONSTRAINT FK_Carac_Reference_idReference FOREIGN KEY (Reference_idReference) REFERENCES Reference (idReference);
ALTER TABLE Media ADD CONSTRAINT FK_Media_DicoMedia_idMedia FOREIGN KEY (DicoMedia_idMedia) REFERENCES DicoMedia (idDicoMedia);
ALTER TABLE Product ADD CONSTRAINT FK_Product_DicoMedia_idProduct FOREIGN KEY (DicoMedia_idProduct) REFERENCES DicoMedia (idDicoMedia);
ALTER TABLE TypeCarac ADD CONSTRAINT FK_TypeCarac_DicoCarac_idCarac FOREIGN KEY (DicoCarac_idCarac) REFERENCES DicoCarac (idDicoCarac);